/* 
 # CustomDataNotification

 This is a standard visible notification. The user sees an alert banner and a badge, while the app
 receives the `document_id` and `shared_by_user_id` when the user taps the notification.

 # SilentNotification

 This payload does not display a visual alert, play a sound, or badge the app. By setting `content-available: 1`,
 it wakes the app up in the background so it can fetch new data or resolve conflicts before the user opens the app again.

 # ActionableNotification

 By providing a `category` string, the system knows to display specific custom action buttons (like "Accept" or "Decline")
 when the user long-presses the notification. The custom `meeting_id` is passed along to the app so it knows which item to act on.

 # RichMediaNotification

 Setting `mutable-content: 1` tells iOS to intercept the push notification and pass it to your
 Notification Service Extension before displaying it. This gives your app a short window of time to download media
 (like an image from the `media_url`) and attach it to the notification banner.

 # FCM Attributes...
 ```
 "gcm.message_id": "0:1625000000000000%1ee659bb1ee659bb",
 "gcm.message_id": "1698765432000000",

 "google.c.a.e": 1,

 "google.c.sender.id": "123456789012",

 "fcm_options": {
   "image": "https://example.com/uploads/photo123.jpg"
 },
 ```

 * **gcm.message_id**: A unique identifier automatically generated by FCM.
 * **google.c.a.e**: A flag (usually 1) indicating that Firebase Analytics is enabled for tracking this push event.
 * **google.c.fid**: The FID is a unique identifier created by the Firebase Installations Service (FIS) for each instance of a Firebase app installation on a device. It replaced the legacy "Instance ID" (IID) that Firebase used in older SDKs.
 * **google.c.sender.id**: key represents the Sender ID of the Firebase project that dispatched the notification.
 * **fcm_options**: A dictionary FCM uses to pass features like the image URL. Your extension intercepts this payload, reads userInfo["fcm_options"]["image"], downloads the image, and attaches it before iOS displays the banner.
 */
