public struct FCMMetadata: Hashable, Sendable {
    /// A unique identifier automatically generated by FCM.
    ///
    /// Attribute Identifier: **gcm.message_id**
    public let messageId: String?

    /// Represents the Sender ID of the Firebase project that dispatched the notification.
    ///
    /// Attribute Identifier: **google.c.sender.id**
    public let senderId: String?

    /// The FID is a unique identifier created by the Firebase Installations Service (FIS) for each
    /// instance of a Firebase app installation on a device. It replaced the legacy "Instance ID" (IID)
    /// that Firebase used in older SDKs.
    ///
    /// Attribute Identifier: **google.c.fid**
    public let installationId: String?

    /// A flag (usually 1) indicating that Firebase Analytics is enabled for tracking this push event.
    ///
    /// Attribute Identifier: **google.c.a.e**
    public let analyticsEnabled: Int?

    public init(
        messageId: String? = nil,
        senderId: String? = nil,
        installationId: String? = nil,
        analyticsEnabled: Int? = nil,
    ) {
        self.messageId = messageId
        self.senderId = senderId
        self.installationId = installationId
        self.analyticsEnabled = analyticsEnabled
    }

    public var payload: UserNotification.Payload {
        var content = UserNotification.Payload()
        if let messageId {
            content[CodingKeys.messageId.rawValue] = .string(messageId)
        }
        if let senderId {
            content[CodingKeys.senderId.rawValue] = .string(senderId)
        }
        if let installationId {
            content[CodingKeys.installationId.rawValue] = .string(installationId)
        }
        if let analyticsEnabled {
            content[CodingKeys.analyticsEnabled.rawValue] = .int(analyticsEnabled)
        }
        return content
    }
}

extension FCMMetadata: Codable {
    enum CodingKeys: String, CodingKey {
        case messageId = "gcm.message_id"
        case senderId = "google.c.sender.id"
        case installationId = "google.c.fid"
        case analyticsEnabled = "google.c.a.e"
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        messageId = try container.decodeIfPresent(String.self, forKey: .messageId)
        senderId = try container.decodeIfPresent(String.self, forKey: .senderId)
        installationId = try container.decodeIfPresent(String.self, forKey: .installationId)

        do {
            analyticsEnabled = try container.decodeIfPresent(Int.self, forKey: .analyticsEnabled)
        } catch DecodingError.typeMismatch {
            if let value = try container.decodeIfPresent(String.self, forKey: .analyticsEnabled) {
                analyticsEnabled = Int(value)
            } else {
                analyticsEnabled = nil
            }
        } catch {
            analyticsEnabled = nil
        }
    }
}
